name: Build & get artifacts

on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Electron Builder Action
        uses: samuelmeuli/action-electron-builder@v1.6.0 
        
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: maven-web-application
          path: /opt

      - name: List Artifacts
        run: ls /opt
